### PR TITLE
Fix compilation errors on node 12

### PR DESCRIPTION
**Pull request by darangi**
The following errors were generated while trying to compile on node 12
```
../src/binding.cpp:33:37: error: too few arguments to function call, single
      argument 'isolate' was not specified
  std::string str(v8str->Utf8Length(), ' ');

../src/binding.cpp:34:27: error: too few arguments to function call, expected at
      least 2, have 1
  v8str->WriteUtf8(&str[0]);
  ~~~~~~~~~~~~~~~~        

../src/binding.cpp:54:37: error: no matching member function for call to
      'ToString'
    return to_std_string(propLocal->ToString());

../src/binding.cpp:76:47: error: too few arguments to function call, single
      argument 'context' was not specified
    MatcherConstructor.Reset(tpl->GetFunction());

../src/binding.cpp:77:73: error: too few arguments to function call, single
      argument 'context' was not specified
    exports->Set(Nan::New("Matcher").ToLocalChecked(), tpl->GetFunction());

../src/binding.cpp:95:46: error: no matching member function for call to
      'ToString'
    std::string query(to_std_string(info[0]->ToString()));

../src/binding.cpp:100:35: error: no matching member function for call to
      'ToObject'
      auto options_obj = info[1]->ToObject();

../src/binding.cpp:162:52: error: no matching member function for call to
      'ToString'
        auto value = to_std_string(values->Get(i)->ToString());

### CODE REVIEW

**Comment by lkashef** [comment]
@darangi Take a look at this https://github.com/atom/nsfw/pull/11, it should help, it looks like you are facing the same issues. In general any PR from any node package adding node 12 support should be a great resource, it's also a good idea to add support for node 12 in the CI as indicated in this PR.

**Comment by lkashef** [comment]
Good job @darangi, go ahead and merge.

**Review by lkashef — APPROVED** [review]
Looks good man! Good job @darangi.

**Comment by darangi** [comment]
@lkashef Thanks!  I just noticed this repo doesn't have CI?

**Pull request merged**
